networks:
  vn1:

services:
  n8n-vn1:
    ports:
      - "${N8N_PORT}:${N8N_PORT}"
    container_name: n8n-vn1
    image: docker.n8n.io/n8nio/n8n:latest
    environment:
      - N8N_HOST=${DOMAIN_NAME}
      - WEBHOOK_URL=${HTTP}://${DOMAIN_NAME}${CATALOG}
      - N8N_PATH=${CATALOG}
      - N8N_PORT=${N8N_PORT}
      - N8N_ENDPOINT_WEBHOOK_TEST=webhook-test
      - N8N_SECURE_COOKIE=false

    volumes:
      - ./data:/home/node/.n8n
    restart: unless-stopped
    networks:
      - vn1
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"