events {}

http {
    server {
        listen 80;
        server_name ai-bot.vn1.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 200 "OK";
        }
    }
}

