events {}

http {
    server {
        listen 80;
        server_name ai-bot.vn1.ru;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 200 "OK";
        }
    }
}


; events {}
;
; http {
;     include       mime.types;
;
;     error_log /var/log/nginx/error.log warn;
;
;     server {
;         listen 80;
;         listen [::]:80;
;
;         server_name ai-bot.vn1.ru;
;
;
;         location /.well-known/acme-challenge/ {
;             root /var/www/certbot;
;         }
;
;
;         location / {
;             return 301 https://ai-bot.vn1.ru$request_uri;
;         }
;
;
;     }
;
;     server {
;         listen 443 ssl;
;         listen [::]:443 ssl;
;         keepalive_timeout   70;
;
;         server_name ai-bot.vn1.ru;
;
;         ssl_certificate     /etc/letsencrypt/live/ai-bot.vn1.ru/fullchain.pem;
;         ssl_certificate_key /etc/letsencrypt/live/ai-bot.vn1.ru/privkey.pem;
;
;         location ~* /(wp-admin|wordpress|shop|oldsite) {
;             return 403;
;         }
;
;         location / {
;             root /usr/share/nginx/html;
;             index index.html;
;             try_files $uri $uri/ /index.html;
;         }
;
;   # Стенды
;
;         location /vn1/ {
;             proxy_pass http://n8n-vn1:5678/;
;
;             proxy_set_header Host $host;
;             proxy_set_header X-Real-IP $remote_addr;
;             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
;         }
;
;         location /api/ {
;             proxy_pass http://backend-vn1:8010/;
;
;             proxy_set_header Host $host;
;             proxy_set_header X-Real-IP $remote_addr;
;             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
;         }
;
;
;         error_page   500 502 503 504  /50x.html;
;
;     }
; }
;
