from typing import Annotated

from fastapi import Body
from pydantic import BaseModel, ConfigDict, Field

from vn1_protocol.sse_protocol import SkillId


SKILL_RUN_REQUEST_EXAMPLE = {
    "thread_id": "local-thread",
    "user_id": "local-user",
    "message_id": "local-message",
    "data": {
        "request_id": "test-gitlab-1",
        "message": "AuthService",
    },
}


class SkillRunData(BaseModel):
    request_id: str = Field(description="Request id generated by api-gateway.", examples=["test-gitlab-1"])
    message: str = Field(description="Search query for GitLab code search.", examples=["AuthService"])


class SkillRunRequest(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                SKILL_RUN_REQUEST_EXAMPLE
            ]
        }
    )

    thread_id: str | None = Field(default=None, description="Chat/thread id from Gateway.")
    user_id: str | None = Field(default=None, description="Authenticated user id from Gateway.")
    message_id: str | None = Field(default=None, description="Assistant message id allocated by Gateway.")
    data: SkillRunData = Field(description="GitLab skill payload.")

    @property
    def request_id(self) -> str:
        return self.data.request_id

    @property
    def message(self) -> str:
        return self.data.message


SkillRunRequestBody = Annotated[
    SkillRunRequest,
    Body(
        openapi_examples={
            "gitlab_code_search": {
                "summary": "GitLab code search",
                "value": SKILL_RUN_REQUEST_EXAMPLE,
            }
        }
    ),
]


class SkillManifestResponse(BaseModel):
    id: SkillId = Field(description="Skill id.", examples=[SkillId.gitlab.value])
    name: str = Field(description="Skill name.", examples=["GitLab Skill"])
    version: str = Field(description="Skill API version.", examples=["0.1.0"])
    capabilities: list[str] = Field(default_factory=list, description="Skill capabilities.")
    stream_endpoint: str = Field(description="SSE stream endpoint path.", examples=["/v1/run/stream"])
    requires_sources: bool = Field(description="Whether skill must answer only with confirmed sources.")
