networks:
  vn1:
    name: vn1

services:
  orchestrator-skill:
    extends:
      file: ./skills/orchestrator-skill/docker-compose.yaml
      service: orchestrator-skill

  gitlab-skill:
    extends:
      file: ./skills/gitlab-skill/docker-compose.yaml
      service: gitlab-skill
