version = 5.2.2
archive_dir = /etc/letsencrypt/archive/ai-bot.vn1.ru
cert = /etc/letsencrypt/live/ai-bot.vn1.ru/cert.pem
privkey = /etc/letsencrypt/live/ai-bot.vn1.ru/privkey.pem
chain = /etc/letsencrypt/live/ai-bot.vn1.ru/chain.pem
fullchain = /etc/letsencrypt/live/ai-bot.vn1.ru/fullchain.pem
[renewalparams]
account = ffb00429c25a0c1739c91abd811c72a0
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
ai-bot.vn1.ru = /var/www/certbot
