name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: OPENAI_API_KEY
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITLAB_AVGR_TOKEN: ${{ secrets.GITLAB_AVGR_TOKEN }}
      ALL_PROXY: ${{ vars.ALL_PROXY }}

    steps:
      - name: Deploy
        run: |
          cd /opt/docker/vn1_bot
          git pull
          sudo -E make run
